version: '3'
services:
  web:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.dev
    image: node1:1.0
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - .:/app