version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1


jobs:
  build-and-push-image:
    executor: aws-cli/default
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup # Install awscli
      - run:
          name: Build Docker image
          command: |
            docker build -t docker-react -f Dockerfile.dev .
      - aws-ecr/build-and-push-image # Push Docker image to ECR
          repo: docker-react # ECR repository name
          tag: "1.0" # Docker image tag
          dockerfile: Dockerfile.dev

  deploy-to-beanstalk:
    executor: aws-cli/default
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup # Install awscli
      - run:
          name: Install ebcli # Install ebcli 
          command: |
            sudo apt-get update && sudo apt-get install python-pip python-dev build-essential 
            sudo pip install --upgrade pip 
            sudo pip install awsebcli --upgrade --ignore-installed six 
            eb --version 
      - run:
          name: Deploy Docker image to Elastic Beanstalk # Deploy Docker image to Elastic Beanstalk 
          command: |
            eb init docker-react --region eu-west-1 --platform "Docker running on 64bit Amazon Linux" # Initialize EB application 
            eb use docker-react-env # Set EB environment name 
            eb deploy --staged # Deploy staged version 

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image
      - deploy-to-beanstalk:
          requires:
            - build-and-push-image