version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-ecr: circleci/aws-ecr@8.2.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  deploy-to-beanstalk:
    executor: aws-cli/default
    context: aws-creds
    steps:
      - checkout
      - eb/setup
      - run:
          name: Deploy Docker image to Elastic Beanstalk # Deploy Docker image to Elastic Beanstalk 
          command: |
            eb init --platform docker --region eu-west-1 --repository react-repo
            eb use docker-react-env
            eb deploy docker-react-env
            eb status

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-cli-version: latest
          context: aws-credentials
          create-repo: true
          dockerfile: Dockerfile.dev
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: react-repo
          source-profile: sourceProfileName
          tag: '1.0'
      - deploy-to-beanstalk:
          requires:
            - aws-ecr/build-and-push-image
