# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.1.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t my-image/docker-react -f Dockerfile .
      - run:
          name: Run Docker container and execute tests
          command: |
            docker run --name my-react-app -e CI=true my-image/docker-react npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
      - eb/deploy:
          context: aws-credentials
          application-name: docker-react
          environment-name: Dockerreact-env
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
